apiVersion: v1
kind: Service
metadata:
  name: livello-mc-prod-svc
  labels:
    app: livello-mc-prod
spec:
  type: NodePort
  selector:
    app: livello-mc-prod
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: livello-mc-prod-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 'livello-mc-prod-ip'
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-edit-in-place: 'true'
  labels:
    app: livello-mc-prod
spec:
  backend:
    serviceName: livello-mc-prod-svc
    servicePort: 8080
  tls:
    - secretName: mc-prod-livello-com-cert
      hosts:
        - 'mc.livello.com'
