apiVersion: v1
kind: Service
metadata:
  name: livello-mc-stage-svc
  labels:
    app: livello-mc-stage
spec:
  type: NodePort
  selector:
    app: livello-mc-stage
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: livello-mc-stage-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 'livello-mc-staging-ip'
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-edit-in-place: 'true'
  labels:
    app: livello-mc-stage
spec:
  backend:
    serviceName: livello-mc-stage-svc
    servicePort: 8080
  tls:
    - secretName: mc-stage-livello-com-cert
      hosts:
        - 'mc-stage.livello.com'
