apiVersion: v1
kind: Service
metadata:
  name: livello-mc-test-svc
  labels:
    app: livello-mc-test
spec:
  type: NodePort
  selector:
    app: livello-mc-test
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: livello-mc-test-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 'livello-mc-test-ip'
    # certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    # certmanager.k8s.io/acme-http01-edit-in-place: 'true'
  labels:
    app: livello-mc-test
spec:
  backend:
    serviceName: livello-mc-test-svc
    servicePort: 8080
  # tls:
  #   - secretName: mc-test-livello-com-cert
  #     hosts:
  #       - 'mc-test.livello.com'
